# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo requirements.txt desde la carpeta app al contenedor
COPY app/requirements.txt /app/

# Instala las dependencias desde el requirements.txt
RUN pip install -r /app/requirements.txt

# Copia el contenido de la carpeta app al contenedor
COPY app/ /app/

# Expón el puerto en el que se ejecutará la aplicación Flask
EXPOSE 5000

# Ejecuta la API dentro del contenedor
CMD ["python", "app.py", "-m flask"]
